PROC SQL;
    CREATE TABLE coworking (
        coworking_id NUMERIC NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        startup_id NUMERIC NOT NULL,
        nr_sali CHAR(255) NOT NULL,
        data_rezerwacji DATETIME NOT NULL
    );

    CREATE TABLE finansowanie (
        finansowanie_id NUMERIC NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        startup_id NUMERIC NOT NULL,
        kwota NUMERIC(8,2) NOT NULL,
        data_przyznania DATE
    );

    CREATE TABLE mentoring (
        mentoring_id NUMERIC NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        startup_id NUMERIC NOT NULL,
        mentor_id NUMERIC NOT NULL,
        data_rozpoczecia DATE
    );

    CREATE TABLE czlonkowie_startupu (
        czlonek_id NUMERIC NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        student_id NUMERIC NOT NULL,
        startup_id NUMERIC NOT NULL,
        rola CHAR(255)
    );

    CREATE TABLE uczestnicy_wydarzen (
        uczestnik_id NUMERIC NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        wydarzenie_id NUMERIC NOT NULL,
        student_id NUMERIC NOT NULL
    );

    CREATE TABLE mentorzy (
        mentor_id NUMERIC NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        imie CHAR(255) NOT NULL,
        nazwisko CHAR(255) NOT NULL,
        specjalizacja CHAR(255)
    );

    CREATE TABLE startupy (
        startup_id NUMERIC NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nazwa CHAR(255) NOT NULL UNIQUE,
        opis CHAR(1024),
        data_rozpoczecia DATE
    );

    CREATE TABLE studenci (
        student_id NUMERIC NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nr_indeksu CHAR(255) NOT NULL UNIQUE,
        imie CHAR(255) NOT NULL,
        nazwisko CHAR(255) NOT NULL,
        email CHAR(255) NOT NULL UNIQUE,
        telefon CHAR(255) NOT NULL UNIQUE
    );

    CREATE TABLE wydarzenia (
        wydarzenie_id NUMERIC NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nazwa CHAR(255) NOT NULL,
        data DATETIME NOT NULL,
        lokalizacja CHAR(255)
    );

    /* Foreign Key Constraints */
    ALTER TABLE mentoring 
        ADD CONSTRAINT mentoring_startup_id_fk FOREIGN KEY (startup_id) REFERENCES startupy (startup_id);
    ALTER TABLE finansowanie 
        ADD CONSTRAINT finansowanie_startup_id_fk FOREIGN KEY (startup_id) REFERENCES startupy (startup_id);
    ALTER TABLE coworking 
        ADD CONSTRAINT coworking_startup_id_fk FOREIGN KEY (startup_id) REFERENCES startupy (startup_id);
    ALTER TABLE czlonkowie_startupu 
        ADD CONSTRAINT czlonkowie_startupu_startup_id_fk FOREIGN KEY (startup_id) REFERENCES startupy (startup_id);
    ALTER TABLE mentoring 
        ADD CONSTRAINT mentoring_mentor_id_fk FOREIGN KEY (mentor_id) REFERENCES mentorzy (mentor_id);
    ALTER TABLE uczestnicy_wydarzen 
        ADD CONSTRAINT uczestnicy_wydarzen_wydarzenie_id_fk FOREIGN KEY (wydarzenie_id) REFERENCES wydarzenia (wydarzenie_id);
    ALTER TABLE uczestnicy_wydarzen 
        ADD CONSTRAINT uczestnicy_wydarzen_student_id_fk FOREIGN KEY (student_id) REFERENCES studenci (student_id);
    ALTER TABLE czlonkowie_startupu 
        ADD CONSTRAINT czlonkowie_startupu_student_id_fk FOREIGN KEY (student_id) REFERENCES studenci (student_id);
QUIT;
