CREATE TABLE ROLE (
    id      INTEGER NOT NULL PRIMARY KEY, 
	nazwa   VARCHAR2(50) NOT NULL UNIQUE
);

INSERT INTO ROLE VALUES (1, 'Admin');
INSERT INTO ROLE VALUES (2, 'User');

CREATE TABLE KONTA (
    id      INTEGER NOT NULL PRIMARY KEY,
    login   VARCHAR2(50) NOT NULL UNIQUE,
    haslo   VARCHAR2(100) NOT NULL,
    rola_id INTEGER NOT NULL
);

INSERT INTO KONTA VALUES (1, 'admin', 'admin', 1);
INSERT INTO KONTA VALUES (2, 'user1', 'haslomaslo', 2);
INSERT INTO KONTA VALUES (3, 'user2', '12345', 2);
INSERT INTO KONTA VALUES (4, 'user3', 'qwerty', 2);